<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegisterWelcomeForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Continue', SubmitType::class, array(
                'label' => "Start your application now!",
                'attr' => array('class' => 'btn btn-primary btn-block', 'formnovalidate' => '', 'style' => 'width: 250px')
            ))
            ->add('step', HiddenType::class, array(
                'data' => 'register_business_info'
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}